"""change Saved model to just id and recipe_id

Revision ID: b4151fbbb6c9
Revises: ff31b5a1c1b0
Create Date: 2018-04-19 16:37:22.311157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4151fbbb6c9'
down_revision = 'ff31b5a1c1b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved', 'title')
    op.drop_column('saved', 'source_url')
    op.drop_column('saved', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('saved', sa.Column('source_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('saved', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
